# Generated by Django 2.0.4 on 2018-04-19 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70, verbose_name='Titulo de la noticia')),
                ('resumen', models.TextField(verbose_name='Resumen de la noticia')),
                ('contenido', models.TextField(verbose_name='Contenido de la noticia')),
                ('fechareg', models.DateTimeField(auto_now_add=True)),
                ('fechaact', models.DateTimeField(auto_now=True)),
                ('imagen', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
