# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_departamento_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('fechareg', models.DateTimeField(auto_now_add=True)),
                ('fechaact', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Empleado')),
            ],
        ),
    ]
