# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(verbose_name='Contenido de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(verbose_name='Resumen de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=70, verbose_name='Titulo de la noticia'),
        ),
    ]
